print(f'{"Desafio 07":=^20}')
aluno = input('Digite o nome do aluno: ')
nota1 = float(input('Digite a primeira nota do aluno: '))
nota2 = float(input('Digite a segudna nota da aluno: '))
print(f'''O aluno, {aluno}\nTem a media de {(nota1+nota2)/2:.1f}''')
